### ISSUE TITLE
samples only work in /arcade/samples subfolder

### ISSUE THREAD

**Issue by passionforpins** [libretro/mame2000-libretro#79]
current lr-mame2000 commit 6ad65bb audio samples ONLY work when I create a samples folder under the arcade folder- home/pi/RetroPie/roms/arcade/samples/
lr-mame2000 not picking up samples in retroarch system folders /home/pi/RetroPie/BIOS/mame2003/samples nor ~/BIOS/mame2000/samples

**Comment by tzachyb** [comment]
Encountered same, contrary to Retropie's documentation.

**Comment by passionforpins** [comment]
I wish I had the brains to compile it myself and redirect samples out of the roms folder :(

**Comment by dankcushions** [comment]
Fixed this in https://github.com/libretro/mame2000-libretro/pull/85 - when it gets merged just update lr-mame2000 from source in retropie :)

**Comment by passionforpins** [comment]
YAY! Super thanks @dankcushions

**Comment by robbalvey** [comment]
I have installed from source and I cannot get samples to work from this folder:
/home/pi/RetroPie/BIOS/mame2000/samples

Can someone please tell me what folder the samples are supposed to go in?

Thank you.

**Comment by passionforpins** [comment]
Works on mine from there but I also have a sample set in the mame2003/samples folder. I believe /home/pi/RetroPie/BIOS/mame2003/samples is the default

**Comment by robbalvey** [comment]
I just tested that and I dropped the samples for Astro Blaster in my /home/pi/RetroPie/BIOS/mame2003/samples folder and it did not work. I know the sample file does work because if I drop it into my MAME4ALL folder /home/pi/RetroPie/roms/mame-mame4all/samples it works using MAME4ALL I just cannot figure out where to put the samples for lr-mame2000 for them to be picked up by the emulation core. 

If you are using mame2000 on your build, can you try deleting your sample file from the /mame2003/samples folder and see if it still works?  And if it does, that means it's pulling that sample file from another folder.

Thanks.

**Comment by robbalvey** [comment]
Update: I just did another pull from source and this time it worked.  My samples are in this folder:
/home/pi/RetroPie/BIOS/mame2000/samples
and I tested to make sure that is the correct folder they need to be in, and yes, the samples now work just fine.

**Comment by passionforpins** [comment]
thumbs up
